---
Name: shopdiscount
---
LeftAndMain:
  extra_requirements_css:
    - shop_discount/css/OrderCouponAdmin.css
Product_OrderItem:
  extensions:
    - DiscountedOrderItem
Discount:
  constraints:
    - ZonesDiscountConstraint
    - CategoriesDiscountConstraint
    - ProductsDiscountConstraint
    - CodeDiscountConstraint
    - GroupDiscountConstraint
    - DatetimeDiscountConstraint
    - ValueDiscountConstraint
    - UseLimitDiscountConstraint

CheckoutPage_Controller:
  extensions:
    - CouponFormCheckoutDecorator